# Generated by Django 2.2.5 on 2019-09-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=300, verbose_name='Маркировка устройства')),
                ('alarm_type', models.CharField(choices=[('siren', 'сирена'), ('speaker', 'громкоговоритель')], max_length=20, verbose_name='Тип устройства')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name=' Адрес устройства')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('alarm_range', models.PositiveIntegerField(verbose_name='Радиус действия (метров)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Подключено ли устройство.')),
                ('turn_on', models.BooleanField(default=False, verbose_name='Состояние "Вкл./выкл"')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
    ]
