# Generated by Django 2.2.5 on 2019-09-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=300, verbose_name='Маркировка')),
                ('alarm_type', models.CharField(choices=[(1, 'siren'), (2, 'loudspeaker')], max_length=20, verbose_name='Тип устройства')),
                ('address', models.CharField(max_length=300, verbose_name=' Адрес устройства')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('alarm_range', models.PositiveIntegerField(verbose_name='Радиус действия (метров)')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
    ]
