# Generated by Django 2.2.5 on 2019-09-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='alarm_type',
            field=models.CharField(choices=[('siren', 'сирена'), ('loudspeaker', 'громкоговоритель')], max_length=20, verbose_name='Тип устройства'),
        ),
    ]
