# Generated by Django 2.2.5 on 2019-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20190927_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Подключено ли устройство.'),
        ),
        migrations.AddField(
            model_name='device',
            name='turn_on',
            field=models.BooleanField(default=False, verbose_name='Состояние "Вкл./выкл"'),
        ),
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name=' Адрес устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='alarm_type',
            field=models.CharField(choices=[('siren', 'сирена'), ('speaker', 'громкоговоритель')], max_length=20, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='label',
            field=models.CharField(blank=True, max_length=300, verbose_name='Маркировка устройства'),
        ),
    ]
